### ISSUE TITLE
eslint-config-airbnb

### ISSUE THREAD

**Issue by fjh8079** [ddhp/react-isomorphic-boilerplate#20]
replace `eslint-config-airbnb-base` with `eslint-config-airbnb`

**Comment by ddhp** [comment]
@penguinfu why do you want to replace eslint-config-airbnb-base?

**Comment by ddhp** [comment]
well done @penguinfu 
next time it's better clarifying the motivation of the issue, instead of only saying action point.

the reason we making this replacement: `eslint-config-airbnb` is  `eslint-config-airbnb-base` plus react related lint.
