### ISSUE TITLE
sass-loader

### ISSUE THREAD

**Issue by bitcoinment** [ddhp/react-isomorphic-boilerplate#29]
Want use **style-loader** with **sass-loader** (for using scss files with variables).
In **webpack.base.js** I changed:

`scssUseLoaders.unshift('style-loader');`
to
`scssUseLoaders.unshift('style-loader?sourceMap', 'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!sass-loader');`

And got an error
```
ERROR in ./src/components/NavWrapper/LeftMenu/theme.scss (./node_modules/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./node_modules/sass-loader/lib/loader.js!./node_modules/css-loader??ref--9-2!./node_modules/postcss-loader/lib??ref--9-3!./node_modules/sass-loader/lib/loader.js??ref--9-4!./src/components/NavWrapper/LeftMenu/theme.scss)
    Module build failed:
      --transition-2: all .2s ease-in-out !important;
                    ^
          Invalid CSS after "....2s ease-in-out": expected "}", was "!important;"
```

**Comment by ddhp** [comment]
this boilerplate has already been using sass-loader, you can see the config for webpack [here](https://github.com/ddhp/react-isomorphic-boilerplate/blob/master/webpack.base.js#L117), so you can directly import scss files without extra setting.

Btw unshifting style-loader here means this loader is applied to every env except `prod`, for the purpose of hot reload.

**Comment by bitcoinment** [comment]
Ok, but why className isn't work?
```
import custom './custom.scss';
...etc....
<div className={custom.demo}>
          Custom styles
</div>
```

Webpack conf:
```
    const scssUseLoaders = [
      {
        loader: 'css-loader',
        options: {
          sourceMap: env !== 'prod',
          localIdentName: '[path]___[name]__[local]___[hash:base64:5]',
          modules: true,
        },
      }, etc....
```

Can you check my [fork here?](https://github.com/bitcoinment/react-isomorphic-boilerplate/blob/master/src/containers/Home/index.js) (Modified only Home/index.js)

**Comment by ddhp** [comment]
So far this boilerplate doesn't have the concept of CSS modules(to be honest, I didn't know this feature before you raise this issue lol, thank you!)

I am now working on implementing CSS modules with [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules), please wait for it.

**Comment by ddhp** [comment]
close due to inactivity
